export const SET_LOADING = 'SET_LOADING'
export const SET_LOADING_FOR_TABLE = 'SET_LOADING_FOR_TABLE'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR'
export const FETCH_SINGLE_COMMENT_SUCCESS = 'FETCH_SINGLE_COMMENT_SUCCESS'
export const FETCH_SINGLE_COMMENT_ERROR = 'FETCH_SINGLE_COMMENT_ERROR'

export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR'
export const PAGE_CLICK = 'PAGE_CLICK'
export const SET_FILTER = 'SET_FILTER'







